version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./www:/var/www
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mariadb
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./www/html/base-laravel:/app
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
  mariadb:
    image: mariadb:10 #10.x latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: testdb
    volumes:
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql